apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nginx
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }} # Clusterip Port
      targetPort: {{ .Values.service.target port}} # Target port of the cluster
      nodePort: {{ .Values.service.nodePort }}  # Include nodePort configuration
  selector:
    app: nginx
    release: {{ .Release.Name }}
