replicaCount: 2

image:
  repository: nginx
  tag: stable
  pullPolicy: IfNotPresent

service:
  type: NodePort  # Set service type to NodePort
  port: 80
  target port: 80
  nodePort: 31000  # Specify the desired nodePort value
