apiVersion: v1
kind: Pod   
metadata:
  name: httpd
  labels:
   node: dev
spec:
  containers:
  - name: httpd
    image: httpd
    ports:
     - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-loadbalancer-service
spec:
  type: LoadBalancer
  selector:
    app: dev
  ports:
    - protocol: TCP
      port: 80             # Port exposed by the service externally
      targetPort: 8080     # Port on the pods that the service forwards traffic to